import type { IFlight } from '../../types/flight.types';

export const FLIGHTS: IFlight[] = [
  {
    logo: '/logos/turkish.svg',
    airline: 'TK143',
    fromSity: 'Sofia',
    fromCode: 'SOF',
    toSity: 'Beijing',
    toCode: 'PEK',
    aircraftReg: 'TC-JFP',
    image: '/flights/turkish.png',
  },
  {
    logo: '/logos/ryanair.svg',
    airline: 'RN1782',
    fromSity: 'Dublin',
    fromCode: 'DUB',
    toSity: 'Larnaca',
    toCode: 'LCA',
    aircraftReg: 'D-AISP',
    image: '/flights/turkish.png',
  },
  {
    logo: '/logos/s7.svg',
    airline: 'S7124',
    fromSity: 'Nice',
    fromCode: 'NCE',
    toSity: 'Tbilisi',
    toCode: 'TBS',
    aircraftReg: 'RA-73415',
    image: '/flights/turkish.png',
  },
  {
    logo: '/logos/swiss.svg',
    airline: 'LX318',
    fromSity: 'Porto',
    fromCode: 'OPO',
    toSity: 'Baku',
    toCode: 'GYD',
    aircraftReg: 'HB-JHK',
    image: '/flights/turkish.png',
  },
  {
    logo: '/logos/lufthansa.svg',
    airline: 'LH401',
    fromSity: 'Burgas',
    fromCode: 'BOJ',
    toSity: 'Muscat',
    toCode: 'MCT',
    aircraftReg: 'D-AHD',
    image: '/flights/turkish.png',
  },
];
